### ISSUE TITLE
Appointment creation fails after disconnect

### ISSUE THREAD

**Issue by dvasilas** [AntidoteDB/calender-app#1]
When disconnecting, and then trying to add a new appointment in "Calendar 1" (left window) the following error occurs, and the appointment is not created:

```
POST /api/0/disconnectNetwork 200 778.590 ms - 15
try to add Appointment {"id":0,"title":"Meeting1","start":"2018-06-27T10:00:00.000Z","end":"2018-06-27T11:00:00.000Z","allDay":false,"description":"","participants":["user1"],"priority":"","comments":["2018.06.26, 14:45:20: created by user1"]} to calendar: Business
Failed to add Appointment Error: Request timed out
    at AntidoteConnection.onRequestTimeout (/Users/dimvas/antidote/calender-app/Application/node_modules/antidote_ts_client/dist/antidoteConnection.js:120:31)
    at Timeout.requests.push.timer._ (/Users/dimvas/antidote/calender-app/Application/node_modules/antidote_ts_client/dist/antidoteConnection.js:163:45)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
POST /api/1/addAppointment 200 1022.515 ms - 16
(node:50616) UnhandledPromiseRejectionWarning: Error: Request timed out
    at AntidoteConnection.onRequestTimeout (/Users/dimvas/antidote/calender-app/Application/node_modules/antidote_ts_client/dist/antidoteConnection.js:120:31)
    at Timeout.requests.push.timer._ (/Users/dimvas/antidote/calender-app/Application/node_modules/antidote_ts_client/dist/antidoteConnection.js:163:45)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
(node:50616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:50616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
try to request updates for participant: user1, calendar: Business
``` 

Note:
The error does not occur when adding a new appointment in "Calendar 2'" (right window) after disconnecting. In that case, the appointment creation succeeds as expected.

**Comment by red17electro** [comment]
Thank you for reporting the issue!

We have looked into it and are working on possible solutions.

**Comment by red17electro** [comment]
After running into troubles trying to solve the main cause of the problem, we decided to use a design solution in order to fix this.

Now, when the "disconnect" button is pressed, the Calendar-1 gets frozen (all actions on it are prohibited) such that only already added appointments into it could be edited (in order to be able to demonstrate the conflict feature). The Celendar-2 remains being active, though. 

I will close this issue for now. However, if this solution will not be found as a satisfying one, we will give it a second thought.
